/* tslint:disable */
/* eslint-disable */
/**
 * Visma eAccounting API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccountBalance
 */
export interface AccountBalance {
    /**
     * 
     * @type {number}
     * @memberof AccountBalance
     */
    accountNumber?: number;
    /**
     * 
     * @type {string}
     * @memberof AccountBalance
     */
    accountName?: string;
    /**
     * 
     * @type {number}
     * @memberof AccountBalance
     */
    balance?: number;
}

export function AccountBalanceFromJSON(json: any): AccountBalance {
    return AccountBalanceFromJSONTyped(json, false);
}

export function AccountBalanceFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountBalance {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'accountNumber': !exists(json, 'AccountNumber') ? undefined : json['AccountNumber'],
        'accountName': !exists(json, 'AccountName') ? undefined : json['AccountName'],
        'balance': !exists(json, 'Balance') ? undefined : json['Balance'],
    };
}

export function AccountBalanceToJSON(value?: AccountBalance | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'AccountNumber': value.accountNumber,
        'AccountName': value.accountName,
        'Balance': value.balance,
    };
}


