/* tslint:disable */
/* eslint-disable */
/**
 * Visma eAccounting API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AllocationPeriodRow
 */
export interface AllocationPeriodRow {
    /**
     * 
     * @type {string}
     * @memberof AllocationPeriodRow
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof AllocationPeriodRow
     */
    allocationPeriodId?: string;
    /**
     * 
     * @type {number}
     * @memberof AllocationPeriodRow
     */
    accountNumber: number;
    /**
     * 
     * @type {number}
     * @memberof AllocationPeriodRow
     */
    amount: number;
    /**
     * 
     * @type {number}
     * @memberof AllocationPeriodRow
     */
    debitCredit: AllocationPeriodRowDebitCreditEnum;
    /**
     * 
     * @type {number}
     * @memberof AllocationPeriodRow
     */
    quantity?: number;
    /**
     * 
     * @type {number}
     * @memberof AllocationPeriodRow
     */
    weight?: number;
}

export function AllocationPeriodRowFromJSON(json: any): AllocationPeriodRow {
    return AllocationPeriodRowFromJSONTyped(json, false);
}

export function AllocationPeriodRowFromJSONTyped(json: any, ignoreDiscriminator: boolean): AllocationPeriodRow {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'Id') ? undefined : json['Id'],
        'allocationPeriodId': !exists(json, 'AllocationPeriodId') ? undefined : json['AllocationPeriodId'],
        'accountNumber': json['AccountNumber'],
        'amount': json['Amount'],
        'debitCredit': json['DebitCredit'],
        'quantity': !exists(json, 'Quantity') ? undefined : json['Quantity'],
        'weight': !exists(json, 'Weight') ? undefined : json['Weight'],
    };
}

export function AllocationPeriodRowToJSON(value?: AllocationPeriodRow | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Id': value.id,
        'AllocationPeriodId': value.allocationPeriodId,
        'AccountNumber': value.accountNumber,
        'Amount': value.amount,
        'DebitCredit': value.debitCredit,
        'Quantity': value.quantity,
        'Weight': value.weight,
    };
}

/**
* @export
* @enum {string}
*/
export enum AllocationPeriodRowDebitCreditEnum {
    NUMBER_1 = 1,
    NUMBER_2 = 2
}


