/* tslint:disable */
/* eslint-disable */
/**
 * Visma eAccounting API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ArticleAccountCoding
 */
export interface ArticleAccountCoding {
    /**
     * 
     * @type {string}
     * @memberof ArticleAccountCoding
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ArticleAccountCoding
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ArticleAccountCoding
     */
    nameEnglish?: string;
    /**
     * 
     * @type {string}
     * @memberof ArticleAccountCoding
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof ArticleAccountCoding
     */
    vatRate?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ArticleAccountCoding
     */
    isActive?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ArticleAccountCoding
     */
    vatRatePercent?: number;
    /**
     * 
     * @type {number}
     * @memberof ArticleAccountCoding
     */
    domesticSalesSubjectToReversedConstructionVatAccountNumber?: number;
    /**
     * 
     * @type {number}
     * @memberof ArticleAccountCoding
     */
    domesticSalesSubjectToVatAccountNumber?: number;
    /**
     * 
     * @type {number}
     * @memberof ArticleAccountCoding
     */
    domesticSalesVatExemptAccountNumber?: number;
    /**
     * 
     * @type {number}
     * @memberof ArticleAccountCoding
     */
    foreignSalesSubjectToMossAccountNumber?: number;
    /**
     * 
     * @type {number}
     * @memberof ArticleAccountCoding
     */
    foreignSalesSubjectToThirdPartySalesAccountNumber?: number;
    /**
     * 
     * @type {number}
     * @memberof ArticleAccountCoding
     */
    foreignSalesSubjectToVatWithinEuAccountNumber?: number;
    /**
     * 
     * @type {number}
     * @memberof ArticleAccountCoding
     */
    foreignSalesVatExemptOutsideEuAccountNumber?: number;
    /**
     * 
     * @type {number}
     * @memberof ArticleAccountCoding
     */
    foreignSalesVatExemptWithinEuAccountNumber?: number;
}

export function ArticleAccountCodingFromJSON(json: any): ArticleAccountCoding {
    return ArticleAccountCodingFromJSONTyped(json, false);
}

export function ArticleAccountCodingFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArticleAccountCoding {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'Id') ? undefined : json['Id'],
        'name': !exists(json, 'Name') ? undefined : json['Name'],
        'nameEnglish': !exists(json, 'NameEnglish') ? undefined : json['NameEnglish'],
        'type': !exists(json, 'Type') ? undefined : json['Type'],
        'vatRate': !exists(json, 'VatRate') ? undefined : json['VatRate'],
        'isActive': !exists(json, 'IsActive') ? undefined : json['IsActive'],
        'vatRatePercent': !exists(json, 'VatRatePercent') ? undefined : json['VatRatePercent'],
        'domesticSalesSubjectToReversedConstructionVatAccountNumber': !exists(json, 'DomesticSalesSubjectToReversedConstructionVatAccountNumber') ? undefined : json['DomesticSalesSubjectToReversedConstructionVatAccountNumber'],
        'domesticSalesSubjectToVatAccountNumber': !exists(json, 'DomesticSalesSubjectToVatAccountNumber') ? undefined : json['DomesticSalesSubjectToVatAccountNumber'],
        'domesticSalesVatExemptAccountNumber': !exists(json, 'DomesticSalesVatExemptAccountNumber') ? undefined : json['DomesticSalesVatExemptAccountNumber'],
        'foreignSalesSubjectToMossAccountNumber': !exists(json, 'ForeignSalesSubjectToMossAccountNumber') ? undefined : json['ForeignSalesSubjectToMossAccountNumber'],
        'foreignSalesSubjectToThirdPartySalesAccountNumber': !exists(json, 'ForeignSalesSubjectToThirdPartySalesAccountNumber') ? undefined : json['ForeignSalesSubjectToThirdPartySalesAccountNumber'],
        'foreignSalesSubjectToVatWithinEuAccountNumber': !exists(json, 'ForeignSalesSubjectToVatWithinEuAccountNumber') ? undefined : json['ForeignSalesSubjectToVatWithinEuAccountNumber'],
        'foreignSalesVatExemptOutsideEuAccountNumber': !exists(json, 'ForeignSalesVatExemptOutsideEuAccountNumber') ? undefined : json['ForeignSalesVatExemptOutsideEuAccountNumber'],
        'foreignSalesVatExemptWithinEuAccountNumber': !exists(json, 'ForeignSalesVatExemptWithinEuAccountNumber') ? undefined : json['ForeignSalesVatExemptWithinEuAccountNumber'],
    };
}

export function ArticleAccountCodingToJSON(value?: ArticleAccountCoding | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Id': value.id,
        'Name': value.name,
        'NameEnglish': value.nameEnglish,
        'Type': value.type,
        'VatRate': value.vatRate,
        'IsActive': value.isActive,
        'VatRatePercent': value.vatRatePercent,
        'DomesticSalesSubjectToReversedConstructionVatAccountNumber': value.domesticSalesSubjectToReversedConstructionVatAccountNumber,
        'DomesticSalesSubjectToVatAccountNumber': value.domesticSalesSubjectToVatAccountNumber,
        'DomesticSalesVatExemptAccountNumber': value.domesticSalesVatExemptAccountNumber,
        'ForeignSalesSubjectToMossAccountNumber': value.foreignSalesSubjectToMossAccountNumber,
        'ForeignSalesSubjectToThirdPartySalesAccountNumber': value.foreignSalesSubjectToThirdPartySalesAccountNumber,
        'ForeignSalesSubjectToVatWithinEuAccountNumber': value.foreignSalesSubjectToVatWithinEuAccountNumber,
        'ForeignSalesVatExemptOutsideEuAccountNumber': value.foreignSalesVatExemptOutsideEuAccountNumber,
        'ForeignSalesVatExemptWithinEuAccountNumber': value.foreignSalesVatExemptWithinEuAccountNumber,
    };
}


