/* tslint:disable */
/* eslint-disable */
/**
 * Visma eAccounting API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ArticleLabel
 */
export interface ArticleLabel {
    /**
     * 
     * @type {string}
     * @memberof ArticleLabel
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ArticleLabel
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ArticleLabel
     */
    description?: string;
}

export function ArticleLabelFromJSON(json: any): ArticleLabel {
    return ArticleLabelFromJSONTyped(json, false);
}

export function ArticleLabelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArticleLabel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'Id') ? undefined : json['Id'],
        'name': !exists(json, 'Name') ? undefined : json['Name'],
        'description': !exists(json, 'Description') ? undefined : json['Description'],
    };
}

export function ArticleLabelToJSON(value?: ArticleLabel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Id': value.id,
        'Name': value.name,
        'Description': value.description,
    };
}


