/* tslint:disable */
/* eslint-disable */
/**
 * Visma eAccounting API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AttachmentResult
 */
export interface AttachmentResult {
    /**
     * Purpose: Id provided by eAccounting
     * @type {string}
     * @memberof AttachmentResult
     */
    readonly id?: string;
    /**
     * = ['image/jpeg' or 'image/png' or 'image/tiff' or 'application/pdf']
     * @type {string}
     * @memberof AttachmentResult
     */
    contentType: string;
    /**
     * 
     * @type {string}
     * @memberof AttachmentResult
     */
    fileName: string;
}

export function AttachmentResultFromJSON(json: any): AttachmentResult {
    return AttachmentResultFromJSONTyped(json, false);
}

export function AttachmentResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): AttachmentResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'Id') ? undefined : json['Id'],
        'contentType': json['ContentType'],
        'fileName': json['FileName'],
    };
}

export function AttachmentResultToJSON(value?: AttachmentResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ContentType': value.contentType,
        'FileName': value.fileName,
    };
}


