/* tslint:disable */
/* eslint-disable */
/**
 * Visma eAccounting API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AttachmentLink
 */
export interface AttachmentLink {
    /**
     * 
     * @type {string}
     * @memberof AttachmentLink
     */
    documentId?: string;
    /**
     * 
     * @type {number}
     * @memberof AttachmentLink
     */
    documentType: AttachmentLinkDocumentTypeEnum;
    /**
     * Source: Get from /v1/attachments.
     * @type {Array<string>}
     * @memberof AttachmentLink
     */
    attachmentIds: Array<string>;
}

export function AttachmentLinkFromJSON(json: any): AttachmentLink {
    return AttachmentLinkFromJSONTyped(json, false);
}

export function AttachmentLinkFromJSONTyped(json: any, ignoreDiscriminator: boolean): AttachmentLink {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'documentId': !exists(json, 'DocumentId') ? undefined : json['DocumentId'],
        'documentType': json['DocumentType'],
        'attachmentIds': json['AttachmentIds'],
    };
}

export function AttachmentLinkToJSON(value?: AttachmentLink | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'DocumentId': value.documentId,
        'DocumentType': value.documentType,
        'AttachmentIds': value.attachmentIds,
    };
}

/**
* @export
* @enum {string}
*/
export enum AttachmentLinkDocumentTypeEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1,
    NUMBER_2 = 2,
    NUMBER_3 = 3,
    NUMBER_4 = 4,
    NUMBER_5 = 5,
    NUMBER_6 = 6
}


