/* tslint:disable */
/* eslint-disable */
/**
 * Visma eAccounting API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CompanyText
 */
export interface CompanyText {
    /**
     * 
     * @type {string}
     * @memberof CompanyText
     */
    customerInvoiceTextDomestic?: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyText
     */
    customerInvoiceTextForeign?: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyText
     */
    orderTextDomestic?: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyText
     */
    orderTextForeign?: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyText
     */
    overDueTextDomestic?: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyText
     */
    overDueTextForeign?: string;
}

export function CompanyTextFromJSON(json: any): CompanyText {
    return CompanyTextFromJSONTyped(json, false);
}

export function CompanyTextFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompanyText {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'customerInvoiceTextDomestic': !exists(json, 'CustomerInvoiceTextDomestic') ? undefined : json['CustomerInvoiceTextDomestic'],
        'customerInvoiceTextForeign': !exists(json, 'CustomerInvoiceTextForeign') ? undefined : json['CustomerInvoiceTextForeign'],
        'orderTextDomestic': !exists(json, 'OrderTextDomestic') ? undefined : json['OrderTextDomestic'],
        'orderTextForeign': !exists(json, 'OrderTextForeign') ? undefined : json['OrderTextForeign'],
        'overDueTextDomestic': !exists(json, 'OverDueTextDomestic') ? undefined : json['OverDueTextDomestic'],
        'overDueTextForeign': !exists(json, 'OverDueTextForeign') ? undefined : json['OverDueTextForeign'],
    };
}

export function CompanyTextToJSON(value?: CompanyText | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'CustomerInvoiceTextDomestic': value.customerInvoiceTextDomestic,
        'CustomerInvoiceTextForeign': value.customerInvoiceTextForeign,
        'OrderTextDomestic': value.orderTextDomestic,
        'OrderTextForeign': value.orderTextForeign,
        'OverDueTextDomestic': value.overDueTextDomestic,
        'OverDueTextForeign': value.overDueTextForeign,
    };
}


