/* tslint:disable */
/* eslint-disable */
/**
 * Visma eAccounting API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CustomerInvoiceListItem
 */
export interface CustomerInvoiceListItem {
    /**
     * 
     * @type {string}
     * @memberof CustomerInvoiceListItem
     */
    id?: string;
    /**
     * 
     * @type {number}
     * @memberof CustomerInvoiceListItem
     */
    invoiceNumber?: number;
    /**
     * 
     * @type {string}
     * @memberof CustomerInvoiceListItem
     */
    customerNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerInvoiceListItem
     */
    customerName?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerInvoiceListItem
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerInvoiceListItem
     */
    invoiceDate?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerInvoiceListItem
     */
    dueDate?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerInvoiceListItem
     */
    deliveryDate?: string;
    /**
     * 
     * @type {number}
     * @memberof CustomerInvoiceListItem
     */
    remainingAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof CustomerInvoiceListItem
     */
    totalAmount?: number;
    /**
     * 
     * @type {string}
     * @memberof CustomerInvoiceListItem
     */
    currencyCode?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerInvoiceListItem
     */
    href?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerInvoiceListItem
     */
    customerInvoiceAddress1?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerInvoiceListItem
     */
    customerInvoiceAddress2?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerInvoiceListItem
     */
    customerInvoiceCity?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerInvoiceListItem
     */
    customerInvoicePostalCode?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerInvoiceListItem
     */
    customerInvoiceCountry?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerInvoiceListItem
     */
    customerEmail?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerInvoiceListItem
     */
    customerCellphone?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerInvoiceListItem
     */
    customerReference?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerInvoiceListItem
     */
    paymentReferenceNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerInvoiceListItem
     */
    ourReference?: string;
    /**
     * 
     * @type {number}
     * @memberof CustomerInvoiceListItem
     */
    remainingAmountInvoiceCurrency?: number;
    /**
     * 
     * @type {string}
     * @memberof CustomerInvoiceListItem
     */
    createdFromDraftId?: string;
    /**
     * 
     * @type {Date}
     * @memberof CustomerInvoiceListItem
     */
    modifiedUtc?: Date;
}

export function CustomerInvoiceListItemFromJSON(json: any): CustomerInvoiceListItem {
    return CustomerInvoiceListItemFromJSONTyped(json, false);
}

export function CustomerInvoiceListItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerInvoiceListItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'Id') ? undefined : json['Id'],
        'invoiceNumber': !exists(json, 'InvoiceNumber') ? undefined : json['InvoiceNumber'],
        'customerNumber': !exists(json, 'CustomerNumber') ? undefined : json['CustomerNumber'],
        'customerName': !exists(json, 'CustomerName') ? undefined : json['CustomerName'],
        'type': !exists(json, 'Type') ? undefined : json['Type'],
        'invoiceDate': !exists(json, 'InvoiceDate') ? undefined : json['InvoiceDate'],
        'dueDate': !exists(json, 'DueDate') ? undefined : json['DueDate'],
        'deliveryDate': !exists(json, 'DeliveryDate') ? undefined : json['DeliveryDate'],
        'remainingAmount': !exists(json, 'RemainingAmount') ? undefined : json['RemainingAmount'],
        'totalAmount': !exists(json, 'TotalAmount') ? undefined : json['TotalAmount'],
        'currencyCode': !exists(json, 'CurrencyCode') ? undefined : json['CurrencyCode'],
        'href': !exists(json, 'Href') ? undefined : json['Href'],
        'customerInvoiceAddress1': !exists(json, 'CustomerInvoiceAddress1') ? undefined : json['CustomerInvoiceAddress1'],
        'customerInvoiceAddress2': !exists(json, 'CustomerInvoiceAddress2') ? undefined : json['CustomerInvoiceAddress2'],
        'customerInvoiceCity': !exists(json, 'CustomerInvoiceCity') ? undefined : json['CustomerInvoiceCity'],
        'customerInvoicePostalCode': !exists(json, 'CustomerInvoicePostalCode') ? undefined : json['CustomerInvoicePostalCode'],
        'customerInvoiceCountry': !exists(json, 'CustomerInvoiceCountry') ? undefined : json['CustomerInvoiceCountry'],
        'customerEmail': !exists(json, 'CustomerEmail') ? undefined : json['CustomerEmail'],
        'customerCellphone': !exists(json, 'CustomerCellphone') ? undefined : json['CustomerCellphone'],
        'customerReference': !exists(json, 'CustomerReference') ? undefined : json['CustomerReference'],
        'paymentReferenceNumber': !exists(json, 'PaymentReferenceNumber') ? undefined : json['PaymentReferenceNumber'],
        'ourReference': !exists(json, 'OurReference') ? undefined : json['OurReference'],
        'remainingAmountInvoiceCurrency': !exists(json, 'RemainingAmountInvoiceCurrency') ? undefined : json['RemainingAmountInvoiceCurrency'],
        'createdFromDraftId': !exists(json, 'CreatedFromDraftId') ? undefined : json['CreatedFromDraftId'],
        'modifiedUtc': !exists(json, 'ModifiedUtc') ? undefined : (new Date(json['ModifiedUtc'])),
    };
}

export function CustomerInvoiceListItemToJSON(value?: CustomerInvoiceListItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Id': value.id,
        'InvoiceNumber': value.invoiceNumber,
        'CustomerNumber': value.customerNumber,
        'CustomerName': value.customerName,
        'Type': value.type,
        'InvoiceDate': value.invoiceDate,
        'DueDate': value.dueDate,
        'DeliveryDate': value.deliveryDate,
        'RemainingAmount': value.remainingAmount,
        'TotalAmount': value.totalAmount,
        'CurrencyCode': value.currencyCode,
        'Href': value.href,
        'CustomerInvoiceAddress1': value.customerInvoiceAddress1,
        'CustomerInvoiceAddress2': value.customerInvoiceAddress2,
        'CustomerInvoiceCity': value.customerInvoiceCity,
        'CustomerInvoicePostalCode': value.customerInvoicePostalCode,
        'CustomerInvoiceCountry': value.customerInvoiceCountry,
        'CustomerEmail': value.customerEmail,
        'CustomerCellphone': value.customerCellphone,
        'CustomerReference': value.customerReference,
        'PaymentReferenceNumber': value.paymentReferenceNumber,
        'OurReference': value.ourReference,
        'RemainingAmountInvoiceCurrency': value.remainingAmountInvoiceCurrency,
        'CreatedFromDraftId': value.createdFromDraftId,
        'ModifiedUtc': value.modifiedUtc === undefined ? undefined : (value.modifiedUtc.toISOString()),
    };
}


