/* tslint:disable */
/* eslint-disable */
/**
 * Visma eAccounting API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CustomerInvoiceRow,
    CustomerInvoiceRowFromJSON,
    CustomerInvoiceRowFromJSONTyped,
    CustomerInvoiceRowToJSON,
    SalesDocumentRotRutReductionPerson,
    SalesDocumentRotRutReductionPersonFromJSON,
    SalesDocumentRotRutReductionPersonFromJSONTyped,
    SalesDocumentRotRutReductionPersonToJSON,
} from './';

/**
 * 
 * @export
 * @interface CustomerInvoice
 */
export interface CustomerInvoice {
    /**
     * 
     * @type {string}
     * @memberof CustomerInvoice
     */
    id?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CustomerInvoice
     */
    euThirdParty: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CustomerInvoice
     */
    isCreditInvoice?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CustomerInvoice
     */
    currencyCode: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerInvoice
     */
    createdByUserId?: string;
    /**
     * 
     * @type {number}
     * @memberof CustomerInvoice
     */
    totalAmount: number;
    /**
     * 
     * @type {number}
     * @memberof CustomerInvoice
     */
    totalVatAmount: number;
    /**
     * 
     * @type {number}
     * @memberof CustomerInvoice
     */
    totalRoundings: number;
    /**
     * 
     * @type {number}
     * @memberof CustomerInvoice
     */
    totalAmountInvoiceCurrency: number;
    /**
     * 
     * @type {string}
     * @memberof CustomerInvoice
     */
    customerId: string;
    /**
     * 
     * @type {Array<CustomerInvoiceRow>}
     * @memberof CustomerInvoice
     */
    rows: Array<CustomerInvoiceRow>;
    /**
     * 
     * @type {Date}
     * @memberof CustomerInvoice
     */
    invoiceDate: Date;
    /**
     * 
     * @type {Date}
     * @memberof CustomerInvoice
     */
    dueDate: Date;
    /**
     * 
     * @type {Date}
     * @memberof CustomerInvoice
     */
    deliveryDate?: Date;
    /**
     * 
     * @type {number}
     * @memberof CustomerInvoice
     */
    rotReducedInvoicingType: CustomerInvoiceRotReducedInvoicingTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof CustomerInvoice
     */
    rotReducedInvoicingAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof CustomerInvoice
     */
    rotReducedInvoicingPercent?: number;
    /**
     * 
     * @type {string}
     * @memberof CustomerInvoice
     */
    rotReducedInvoicingPropertyName?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerInvoice
     */
    rotReducedInvoicingOrgNumber?: string;
    /**
     * 
     * @type {Array<SalesDocumentRotRutReductionPerson>}
     * @memberof CustomerInvoice
     */
    persons?: Array<SalesDocumentRotRutReductionPerson>;
    /**
     * 
     * @type {boolean}
     * @memberof CustomerInvoice
     */
    rotReducedInvoicingAutomaticDistribution?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CustomerInvoice
     */
    electronicReference?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerInvoice
     */
    electronicAddress?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerInvoice
     */
    ediServiceDelivererId?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerInvoice
     */
    ourReference?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerInvoice
     */
    yourReference?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerInvoice
     */
    invoiceCustomerName: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerInvoice
     */
    invoiceAddress1?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerInvoice
     */
    invoiceAddress2?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerInvoice
     */
    invoicePostalCode: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerInvoice
     */
    invoiceCity: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerInvoice
     */
    invoiceCountryCode: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerInvoice
     */
    deliveryCustomerName?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerInvoice
     */
    deliveryAddress1?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerInvoice
     */
    deliveryAddress2?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerInvoice
     */
    deliveryPostalCode?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerInvoice
     */
    deliveryCity?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerInvoice
     */
    deliveryCountryCode?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerInvoice
     */
    deliveryMethodName?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerInvoice
     */
    deliveryTermName?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerInvoice
     */
    deliveryMethodCode?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerInvoice
     */
    deliveryTermCode?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CustomerInvoice
     */
    customerIsPrivatePerson: boolean;
    /**
     * 
     * @type {string}
     * @memberof CustomerInvoice
     */
    termsOfPaymentId: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerInvoice
     */
    customerEmail?: string;
    /**
     * 
     * @type {number}
     * @memberof CustomerInvoice
     */
    invoiceNumber?: number;
    /**
     * 
     * @type {string}
     * @memberof CustomerInvoice
     */
    customerNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerInvoice
     */
    paymentReferenceNumber?: string;
    /**
     * 
     * @type {number}
     * @memberof CustomerInvoice
     */
    rotPropertyType?: number;
    /**
     * 
     * @type {number}
     * @memberof CustomerInvoice
     */
    workHouseOtherCosts?: number;
    /**
     * 
     * @type {number}
     * @memberof CustomerInvoice
     */
    remainingAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof CustomerInvoice
     */
    remainingAmountInvoiceCurrency?: number;
    /**
     * 
     * @type {string}
     * @memberof CustomerInvoice
     */
    referringInvoiceId?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerInvoice
     */
    voucherNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerInvoice
     */
    voucherId?: string;
}

export function CustomerInvoiceFromJSON(json: any): CustomerInvoice {
    return CustomerInvoiceFromJSONTyped(json, false);
}

export function CustomerInvoiceFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerInvoice {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'Id') ? undefined : json['Id'],
        'euThirdParty': json['EuThirdParty'],
        'isCreditInvoice': !exists(json, 'IsCreditInvoice') ? undefined : json['IsCreditInvoice'],
        'currencyCode': json['CurrencyCode'],
        'createdByUserId': !exists(json, 'CreatedByUserId') ? undefined : json['CreatedByUserId'],
        'totalAmount': json['TotalAmount'],
        'totalVatAmount': json['TotalVatAmount'],
        'totalRoundings': json['TotalRoundings'],
        'totalAmountInvoiceCurrency': json['TotalAmountInvoiceCurrency'],
        'customerId': json['CustomerId'],
        'rows': ((json['Rows'] as Array<any>).map(CustomerInvoiceRowFromJSON)),
        'invoiceDate': (new Date(json['InvoiceDate'])),
        'dueDate': (new Date(json['DueDate'])),
        'deliveryDate': !exists(json, 'DeliveryDate') ? undefined : (new Date(json['DeliveryDate'])),
        'rotReducedInvoicingType': json['RotReducedInvoicingType'],
        'rotReducedInvoicingAmount': !exists(json, 'RotReducedInvoicingAmount') ? undefined : json['RotReducedInvoicingAmount'],
        'rotReducedInvoicingPercent': !exists(json, 'RotReducedInvoicingPercent') ? undefined : json['RotReducedInvoicingPercent'],
        'rotReducedInvoicingPropertyName': !exists(json, 'RotReducedInvoicingPropertyName') ? undefined : json['RotReducedInvoicingPropertyName'],
        'rotReducedInvoicingOrgNumber': !exists(json, 'RotReducedInvoicingOrgNumber') ? undefined : json['RotReducedInvoicingOrgNumber'],
        'persons': !exists(json, 'Persons') ? undefined : ((json['Persons'] as Array<any>).map(SalesDocumentRotRutReductionPersonFromJSON)),
        'rotReducedInvoicingAutomaticDistribution': !exists(json, 'RotReducedInvoicingAutomaticDistribution') ? undefined : json['RotReducedInvoicingAutomaticDistribution'],
        'electronicReference': !exists(json, 'ElectronicReference') ? undefined : json['ElectronicReference'],
        'electronicAddress': !exists(json, 'ElectronicAddress') ? undefined : json['ElectronicAddress'],
        'ediServiceDelivererId': !exists(json, 'EdiServiceDelivererId') ? undefined : json['EdiServiceDelivererId'],
        'ourReference': !exists(json, 'OurReference') ? undefined : json['OurReference'],
        'yourReference': !exists(json, 'YourReference') ? undefined : json['YourReference'],
        'invoiceCustomerName': json['InvoiceCustomerName'],
        'invoiceAddress1': !exists(json, 'InvoiceAddress1') ? undefined : json['InvoiceAddress1'],
        'invoiceAddress2': !exists(json, 'InvoiceAddress2') ? undefined : json['InvoiceAddress2'],
        'invoicePostalCode': json['InvoicePostalCode'],
        'invoiceCity': json['InvoiceCity'],
        'invoiceCountryCode': json['InvoiceCountryCode'],
        'deliveryCustomerName': !exists(json, 'DeliveryCustomerName') ? undefined : json['DeliveryCustomerName'],
        'deliveryAddress1': !exists(json, 'DeliveryAddress1') ? undefined : json['DeliveryAddress1'],
        'deliveryAddress2': !exists(json, 'DeliveryAddress2') ? undefined : json['DeliveryAddress2'],
        'deliveryPostalCode': !exists(json, 'DeliveryPostalCode') ? undefined : json['DeliveryPostalCode'],
        'deliveryCity': !exists(json, 'DeliveryCity') ? undefined : json['DeliveryCity'],
        'deliveryCountryCode': !exists(json, 'DeliveryCountryCode') ? undefined : json['DeliveryCountryCode'],
        'deliveryMethodName': !exists(json, 'DeliveryMethodName') ? undefined : json['DeliveryMethodName'],
        'deliveryTermName': !exists(json, 'DeliveryTermName') ? undefined : json['DeliveryTermName'],
        'deliveryMethodCode': !exists(json, 'DeliveryMethodCode') ? undefined : json['DeliveryMethodCode'],
        'deliveryTermCode': !exists(json, 'DeliveryTermCode') ? undefined : json['DeliveryTermCode'],
        'customerIsPrivatePerson': json['CustomerIsPrivatePerson'],
        'termsOfPaymentId': json['TermsOfPaymentId'],
        'customerEmail': !exists(json, 'CustomerEmail') ? undefined : json['CustomerEmail'],
        'invoiceNumber': !exists(json, 'InvoiceNumber') ? undefined : json['InvoiceNumber'],
        'customerNumber': !exists(json, 'CustomerNumber') ? undefined : json['CustomerNumber'],
        'paymentReferenceNumber': !exists(json, 'PaymentReferenceNumber') ? undefined : json['PaymentReferenceNumber'],
        'rotPropertyType': !exists(json, 'RotPropertyType') ? undefined : json['RotPropertyType'],
        'workHouseOtherCosts': !exists(json, 'WorkHouseOtherCosts') ? undefined : json['WorkHouseOtherCosts'],
        'remainingAmount': !exists(json, 'RemainingAmount') ? undefined : json['RemainingAmount'],
        'remainingAmountInvoiceCurrency': !exists(json, 'RemainingAmountInvoiceCurrency') ? undefined : json['RemainingAmountInvoiceCurrency'],
        'referringInvoiceId': !exists(json, 'ReferringInvoiceId') ? undefined : json['ReferringInvoiceId'],
        'voucherNumber': !exists(json, 'VoucherNumber') ? undefined : json['VoucherNumber'],
        'voucherId': !exists(json, 'VoucherId') ? undefined : json['VoucherId'],
    };
}

export function CustomerInvoiceToJSON(value?: CustomerInvoice | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Id': value.id,
        'EuThirdParty': value.euThirdParty,
        'IsCreditInvoice': value.isCreditInvoice,
        'CurrencyCode': value.currencyCode,
        'CreatedByUserId': value.createdByUserId,
        'TotalAmount': value.totalAmount,
        'TotalVatAmount': value.totalVatAmount,
        'TotalRoundings': value.totalRoundings,
        'TotalAmountInvoiceCurrency': value.totalAmountInvoiceCurrency,
        'CustomerId': value.customerId,
        'Rows': ((value.rows as Array<any>).map(CustomerInvoiceRowToJSON)),
        'InvoiceDate': (value.invoiceDate.toISOString()),
        'DueDate': (value.dueDate.toISOString()),
        'DeliveryDate': value.deliveryDate === undefined ? undefined : (value.deliveryDate.toISOString()),
        'RotReducedInvoicingType': value.rotReducedInvoicingType,
        'RotReducedInvoicingAmount': value.rotReducedInvoicingAmount,
        'RotReducedInvoicingPercent': value.rotReducedInvoicingPercent,
        'RotReducedInvoicingPropertyName': value.rotReducedInvoicingPropertyName,
        'RotReducedInvoicingOrgNumber': value.rotReducedInvoicingOrgNumber,
        'Persons': value.persons === undefined ? undefined : ((value.persons as Array<any>).map(SalesDocumentRotRutReductionPersonToJSON)),
        'RotReducedInvoicingAutomaticDistribution': value.rotReducedInvoicingAutomaticDistribution,
        'ElectronicReference': value.electronicReference,
        'ElectronicAddress': value.electronicAddress,
        'EdiServiceDelivererId': value.ediServiceDelivererId,
        'OurReference': value.ourReference,
        'YourReference': value.yourReference,
        'InvoiceCustomerName': value.invoiceCustomerName,
        'InvoiceAddress1': value.invoiceAddress1,
        'InvoiceAddress2': value.invoiceAddress2,
        'InvoicePostalCode': value.invoicePostalCode,
        'InvoiceCity': value.invoiceCity,
        'InvoiceCountryCode': value.invoiceCountryCode,
        'DeliveryCustomerName': value.deliveryCustomerName,
        'DeliveryAddress1': value.deliveryAddress1,
        'DeliveryAddress2': value.deliveryAddress2,
        'DeliveryPostalCode': value.deliveryPostalCode,
        'DeliveryCity': value.deliveryCity,
        'DeliveryCountryCode': value.deliveryCountryCode,
        'DeliveryMethodName': value.deliveryMethodName,
        'DeliveryTermName': value.deliveryTermName,
        'DeliveryMethodCode': value.deliveryMethodCode,
        'DeliveryTermCode': value.deliveryTermCode,
        'CustomerIsPrivatePerson': value.customerIsPrivatePerson,
        'TermsOfPaymentId': value.termsOfPaymentId,
        'CustomerEmail': value.customerEmail,
        'InvoiceNumber': value.invoiceNumber,
        'CustomerNumber': value.customerNumber,
        'PaymentReferenceNumber': value.paymentReferenceNumber,
        'RotPropertyType': value.rotPropertyType,
        'WorkHouseOtherCosts': value.workHouseOtherCosts,
        'RemainingAmount': value.remainingAmount,
        'RemainingAmountInvoiceCurrency': value.remainingAmountInvoiceCurrency,
        'ReferringInvoiceId': value.referringInvoiceId,
        'VoucherNumber': value.voucherNumber,
        'VoucherId': value.voucherId,
    };
}

/**
* @export
* @enum {string}
*/
export enum CustomerInvoiceRotReducedInvoicingTypeEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1,
    NUMBER_2 = 2
}


