/* tslint:disable */
/* eslint-disable */
/**
 * Visma eAccounting API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CustomerListItem
 */
export interface CustomerListItem {
    /**
     * 
     * @type {string}
     * @memberof CustomerListItem
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerListItem
     */
    customerNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerListItem
     */
    corporateIdentityNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerListItem
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerListItem
     */
    href?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CustomerListItem
     */
    isActive?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof CustomerListItem
     */
    modifiedUtc?: Date;
    /**
     * 
     * @type {string}
     * @memberof CustomerListItem
     */
    email?: string;
}

export function CustomerListItemFromJSON(json: any): CustomerListItem {
    return CustomerListItemFromJSONTyped(json, false);
}

export function CustomerListItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerListItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'Id') ? undefined : json['Id'],
        'customerNumber': !exists(json, 'CustomerNumber') ? undefined : json['CustomerNumber'],
        'corporateIdentityNumber': !exists(json, 'CorporateIdentityNumber') ? undefined : json['CorporateIdentityNumber'],
        'name': !exists(json, 'Name') ? undefined : json['Name'],
        'href': !exists(json, 'Href') ? undefined : json['Href'],
        'isActive': !exists(json, 'IsActive') ? undefined : json['IsActive'],
        'modifiedUtc': !exists(json, 'ModifiedUtc') ? undefined : (new Date(json['ModifiedUtc'])),
        'email': !exists(json, 'Email') ? undefined : json['Email'],
    };
}

export function CustomerListItemToJSON(value?: CustomerListItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Id': value.id,
        'CustomerNumber': value.customerNumber,
        'CorporateIdentityNumber': value.corporateIdentityNumber,
        'Name': value.name,
        'Href': value.href,
        'IsActive': value.isActive,
        'ModifiedUtc': value.modifiedUtc === undefined ? undefined : (value.modifiedUtc.toISOString()),
        'Email': value.email,
    };
}


