/* tslint:disable */
/* eslint-disable */
/**
 * Visma eAccounting API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CustomerInvoiceDraftRow
 */
export interface CustomerInvoiceDraftRow {
    /**
     * 
     * @type {number}
     * @memberof CustomerInvoiceDraftRow
     */
    lineNumber: number;
    /**
     * Source: Get from /v1/articles. Required if IsTextRow is false
     * @type {string}
     * @memberof CustomerInvoiceDraftRow
     */
    articleId?: string;
    /**
     * Purpose: Returns the article number from the entered ArticleId
     * @type {string}
     * @memberof CustomerInvoiceDraftRow
     */
    articleNumber?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CustomerInvoiceDraftRow
     */
    isTextRow: boolean;
    /**
     * Max length: 2000. Sets the article name
     * @type {string}
     * @memberof CustomerInvoiceDraftRow
     */
    text: string;
    /**
     * Format: 2 decimals allowed if the customer is domestic or 4 decimals if foreign
     * @type {number}
     * @memberof CustomerInvoiceDraftRow
     */
    unitPrice?: number;
    /**
     * Format: 4 decimals allowed
     * @type {number}
     * @memberof CustomerInvoiceDraftRow
     */
    discountPercentage?: number;
    /**
     * Format: 2 decimals
     * @type {number}
     * @memberof CustomerInvoiceDraftRow
     */
    quantity?: number;
    /**
     * 
     * @type {number}
     * @memberof CustomerInvoiceDraftRow
     */
    workCostType?: number;
    /**
     * 
     * @type {boolean}
     * @memberof CustomerInvoiceDraftRow
     */
    isWorkCost?: boolean;
    /**
     * 
     * @type {number}
     * @memberof CustomerInvoiceDraftRow
     */
    workHours?: number;
    /**
     * 
     * @type {number}
     * @memberof CustomerInvoiceDraftRow
     */
    materialCosts?: number;
    /**
     * 
     * @type {boolean}
     * @memberof CustomerInvoiceDraftRow
     */
    isVatFree: boolean;
    /**
     * Source: Get from /v1/costcenteritems
     * @type {string}
     * @memberof CustomerInvoiceDraftRow
     */
    costCenterItemId1?: string;
    /**
     * Source: Get from /v1/costcenteritems
     * @type {string}
     * @memberof CustomerInvoiceDraftRow
     */
    costCenterItemId2?: string;
    /**
     * Source: Get from /v1/costcenteritems
     * @type {string}
     * @memberof CustomerInvoiceDraftRow
     */
    costCenterItemId3?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerInvoiceDraftRow
     */
    projectId?: string;
}

export function CustomerInvoiceDraftRowFromJSON(json: any): CustomerInvoiceDraftRow {
    return CustomerInvoiceDraftRowFromJSONTyped(json, false);
}

export function CustomerInvoiceDraftRowFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerInvoiceDraftRow {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'lineNumber': json['LineNumber'],
        'articleId': !exists(json, 'ArticleId') ? undefined : json['ArticleId'],
        'articleNumber': !exists(json, 'ArticleNumber') ? undefined : json['ArticleNumber'],
        'isTextRow': json['IsTextRow'],
        'text': json['Text'],
        'unitPrice': !exists(json, 'UnitPrice') ? undefined : json['UnitPrice'],
        'discountPercentage': !exists(json, 'DiscountPercentage') ? undefined : json['DiscountPercentage'],
        'quantity': !exists(json, 'Quantity') ? undefined : json['Quantity'],
        'workCostType': !exists(json, 'WorkCostType') ? undefined : json['WorkCostType'],
        'isWorkCost': !exists(json, 'IsWorkCost') ? undefined : json['IsWorkCost'],
        'workHours': !exists(json, 'WorkHours') ? undefined : json['WorkHours'],
        'materialCosts': !exists(json, 'MaterialCosts') ? undefined : json['MaterialCosts'],
        'isVatFree': json['IsVatFree'],
        'costCenterItemId1': !exists(json, 'CostCenterItemId1') ? undefined : json['CostCenterItemId1'],
        'costCenterItemId2': !exists(json, 'CostCenterItemId2') ? undefined : json['CostCenterItemId2'],
        'costCenterItemId3': !exists(json, 'CostCenterItemId3') ? undefined : json['CostCenterItemId3'],
        'projectId': !exists(json, 'ProjectId') ? undefined : json['ProjectId'],
    };
}

export function CustomerInvoiceDraftRowToJSON(value?: CustomerInvoiceDraftRow | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'LineNumber': value.lineNumber,
        'ArticleId': value.articleId,
        'ArticleNumber': value.articleNumber,
        'IsTextRow': value.isTextRow,
        'Text': value.text,
        'UnitPrice': value.unitPrice,
        'DiscountPercentage': value.discountPercentage,
        'Quantity': value.quantity,
        'WorkCostType': value.workCostType,
        'IsWorkCost': value.isWorkCost,
        'WorkHours': value.workHours,
        'MaterialCosts': value.materialCosts,
        'IsVatFree': value.isVatFree,
        'CostCenterItemId1': value.costCenterItemId1,
        'CostCenterItemId2': value.costCenterItemId2,
        'CostCenterItemId3': value.costCenterItemId3,
        'ProjectId': value.projectId,
    };
}


