/* tslint:disable */
/* eslint-disable */
/**
 * Visma eAccounting API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeliveryMethod
 */
export interface DeliveryMethod {
    /**
     * 
     * @type {string}
     * @memberof DeliveryMethod
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof DeliveryMethod
     */
    code?: string;
    /**
     * 
     * @type {string}
     * @memberof DeliveryMethod
     */
    id?: string;
}

export function DeliveryMethodFromJSON(json: any): DeliveryMethod {
    return DeliveryMethodFromJSONTyped(json, false);
}

export function DeliveryMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeliveryMethod {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'Name') ? undefined : json['Name'],
        'code': !exists(json, 'Code') ? undefined : json['Code'],
        'id': !exists(json, 'Id') ? undefined : json['Id'],
    };
}

export function DeliveryMethodToJSON(value?: DeliveryMethod | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Name': value.name,
        'Code': value.code,
        'Id': value.id,
    };
}


