/* tslint:disable */
/* eslint-disable */
/**
 * Visma eAccounting API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeliveryTerm
 */
export interface DeliveryTerm {
    /**
     * 
     * @type {string}
     * @memberof DeliveryTerm
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof DeliveryTerm
     */
    code?: string;
    /**
     * 
     * @type {string}
     * @memberof DeliveryTerm
     */
    id?: string;
}

export function DeliveryTermFromJSON(json: any): DeliveryTerm {
    return DeliveryTermFromJSONTyped(json, false);
}

export function DeliveryTermFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeliveryTerm {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'Name') ? undefined : json['Name'],
        'code': !exists(json, 'Code') ? undefined : json['Code'],
        'id': !exists(json, 'Id') ? undefined : json['Id'],
    };
}

export function DeliveryTermToJSON(value?: DeliveryTerm | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Name': value.name,
        'Code': value.code,
        'Id': value.id,
    };
}


