/* tslint:disable */
/* eslint-disable */
/**
 * Visma eAccounting API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FiscalYear
 */
export interface FiscalYear {
    /**
     * 
     * @type {string}
     * @memberof FiscalYear
     */
    id?: string;
    /**
     * 
     * @type {Date}
     * @memberof FiscalYear
     */
    startDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof FiscalYear
     */
    endDate?: Date;
}

export function FiscalYearFromJSON(json: any): FiscalYear {
    return FiscalYearFromJSONTyped(json, false);
}

export function FiscalYearFromJSONTyped(json: any, ignoreDiscriminator: boolean): FiscalYear {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'Id') ? undefined : json['Id'],
        'startDate': !exists(json, 'StartDate') ? undefined : (new Date(json['StartDate'])),
        'endDate': !exists(json, 'EndDate') ? undefined : (new Date(json['EndDate'])),
    };
}

export function FiscalYearToJSON(value?: FiscalYear | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Id': value.id,
        'StartDate': value.startDate === undefined ? undefined : (value.startDate.toISOString()),
        'EndDate': value.endDate === undefined ? undefined : (value.endDate.toISOString()),
    };
}


