/* tslint:disable */
/* eslint-disable */
/**
 * Visma eAccounting API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ForeignPaymentCode
 */
export interface ForeignPaymentCode {
    /**
     * 
     * @type {number}
     * @memberof ForeignPaymentCode
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ForeignPaymentCode
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof ForeignPaymentCode
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ForeignPaymentCode
     */
    countryCode?: string;
}

export function ForeignPaymentCodeFromJSON(json: any): ForeignPaymentCode {
    return ForeignPaymentCodeFromJSONTyped(json, false);
}

export function ForeignPaymentCodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ForeignPaymentCode {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'Code') ? undefined : json['Code'],
        'description': !exists(json, 'Description') ? undefined : json['Description'],
        'id': !exists(json, 'Id') ? undefined : json['Id'],
        'countryCode': !exists(json, 'CountryCode') ? undefined : json['CountryCode'],
    };
}

export function ForeignPaymentCodeToJSON(value?: ForeignPaymentCode | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Code': value.code,
        'Description': value.description,
        'Id': value.id,
        'CountryCode': value.countryCode,
    };
}


