/* tslint:disable */
/* eslint-disable */
/**
 * Visma eAccounting API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrderRow
 */
export interface OrderRow {
    /**
     * 
     * @type {number}
     * @memberof OrderRow
     */
    lineNumber: number;
    /**
     * Format: 2 decimals
     * @type {number}
     * @memberof OrderRow
     */
    deliveredQuantity?: number;
    /**
     * 
     * @type {string}
     * @memberof OrderRow
     */
    articleId?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderRow
     */
    articleNumber?: string;
    /**
     * 
     * @type {boolean}
     * @memberof OrderRow
     */
    isTextRow: boolean;
    /**
     * 
     * @type {string}
     * @memberof OrderRow
     */
    text: string;
    /**
     * Format: 2 decimals
     * @type {number}
     * @memberof OrderRow
     */
    unitPrice?: number;
    /**
     * Format: 2 decimals
     * @type {number}
     * @memberof OrderRow
     */
    discountPercentage?: number;
    /**
     * Format: 4 decimals
     * @type {number}
     * @memberof OrderRow
     */
    quantity?: number;
    /**
     * 
     * @type {number}
     * @memberof OrderRow
     */
    workCostType?: number;
    /**
     * 
     * @type {boolean}
     * @memberof OrderRow
     */
    isWorkCost: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof OrderRow
     */
    isVatFree: boolean;
    /**
     * Source: Get from /v1/costcenters
     * @type {string}
     * @memberof OrderRow
     */
    costCenterItemId1?: string;
    /**
     * Source: Get from /v1/costcenters
     * @type {string}
     * @memberof OrderRow
     */
    costCenterItemId2?: string;
    /**
     * Source: Get from /v1/costcenters
     * @type {string}
     * @memberof OrderRow
     */
    costCenterItemId3?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderRow
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderRow
     */
    projectId?: string;
}

export function OrderRowFromJSON(json: any): OrderRow {
    return OrderRowFromJSONTyped(json, false);
}

export function OrderRowFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderRow {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'lineNumber': json['LineNumber'],
        'deliveredQuantity': !exists(json, 'DeliveredQuantity') ? undefined : json['DeliveredQuantity'],
        'articleId': !exists(json, 'ArticleId') ? undefined : json['ArticleId'],
        'articleNumber': !exists(json, 'ArticleNumber') ? undefined : json['ArticleNumber'],
        'isTextRow': json['IsTextRow'],
        'text': json['Text'],
        'unitPrice': !exists(json, 'UnitPrice') ? undefined : json['UnitPrice'],
        'discountPercentage': !exists(json, 'DiscountPercentage') ? undefined : json['DiscountPercentage'],
        'quantity': !exists(json, 'Quantity') ? undefined : json['Quantity'],
        'workCostType': !exists(json, 'WorkCostType') ? undefined : json['WorkCostType'],
        'isWorkCost': json['IsWorkCost'],
        'isVatFree': json['IsVatFree'],
        'costCenterItemId1': !exists(json, 'CostCenterItemId1') ? undefined : json['CostCenterItemId1'],
        'costCenterItemId2': !exists(json, 'CostCenterItemId2') ? undefined : json['CostCenterItemId2'],
        'costCenterItemId3': !exists(json, 'CostCenterItemId3') ? undefined : json['CostCenterItemId3'],
        'id': !exists(json, 'Id') ? undefined : json['Id'],
        'projectId': !exists(json, 'ProjectId') ? undefined : json['ProjectId'],
    };
}

export function OrderRowToJSON(value?: OrderRow | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'LineNumber': value.lineNumber,
        'DeliveredQuantity': value.deliveredQuantity,
        'ArticleId': value.articleId,
        'ArticleNumber': value.articleNumber,
        'IsTextRow': value.isTextRow,
        'Text': value.text,
        'UnitPrice': value.unitPrice,
        'DiscountPercentage': value.discountPercentage,
        'Quantity': value.quantity,
        'WorkCostType': value.workCostType,
        'IsWorkCost': value.isWorkCost,
        'IsVatFree': value.isVatFree,
        'CostCenterItemId1': value.costCenterItemId1,
        'CostCenterItemId2': value.costCenterItemId2,
        'CostCenterItemId3': value.costCenterItemId3,
        'Id': value.id,
        'ProjectId': value.projectId,
    };
}


