/* tslint:disable */
/* eslint-disable */
/**
 * Visma eAccounting API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    OrderRow,
    OrderRowFromJSON,
    OrderRowFromJSONTyped,
    OrderRowToJSON,
    SalesDocumentRotRutReductionPerson,
    SalesDocumentRotRutReductionPersonFromJSON,
    SalesDocumentRotRutReductionPersonFromJSONTyped,
    SalesDocumentRotRutReductionPersonToJSON,
} from './';

/**
 * 
 * @export
 * @interface Order
 */
export interface Order {
    /**
     * Purpose: Unique Id provided by eAccounting
     * @type {string}
     * @memberof Order
     */
    readonly id?: string;
    /**
     * Format: 2 decimals
     * @type {number}
     * @memberof Order
     */
    amount: number;
    /**
     * Get from /v1/customerlistitems
     * @type {string}
     * @memberof Order
     */
    customerId: string;
    /**
     * Max length: 3 characters
     * @type {string}
     * @memberof Order
     */
    currencyCode: string;
    /**
     * Format: 2 decimals
     * @type {number}
     * @memberof Order
     */
    vatAmount: number;
    /**
     * Format: 2 decimals
     * @type {number}
     * @memberof Order
     */
    roundingsAmount: number;
    /**
     * Format: 2 decimals
     * @type {number}
     * @memberof Order
     */
    deliveredAmount?: number;
    /**
     * Format: 2 decimals
     * @type {number}
     * @memberof Order
     */
    deliveredVatAmount?: number;
    /**
     * Format: 2 decimals
     * @type {number}
     * @memberof Order
     */
    deliveredRoundingsAmount?: number;
    /**
     * Max length: 50 characters
     * @type {string}
     * @memberof Order
     */
    deliveryCustomerName?: string;
    /**
     * Max length: 50 characters
     * @type {string}
     * @memberof Order
     */
    deliveryAddress1?: string;
    /**
     * Max length: 50 characters
     * @type {string}
     * @memberof Order
     */
    deliveryAddress2?: string;
    /**
     * Max length: 10 characters
     * @type {string}
     * @memberof Order
     */
    deliveryPostalCode?: string;
    /**
     * Max length: 50 characters
     * @type {string}
     * @memberof Order
     */
    deliveryCity?: string;
    /**
     * Max length: 2 characters
     * @type {string}
     * @memberof Order
     */
    deliveryCountryCode?: string;
    /**
     * Max length: 50 characters
     * @type {string}
     * @memberof Order
     */
    yourReference?: string;
    /**
     * Max length: 50 characters
     * @type {string}
     * @memberof Order
     */
    ourReference?: string;
    /**
     * Max length: 50 characters
     * @type {string}
     * @memberof Order
     */
    invoiceAddress1?: string;
    /**
     * Max length: 50 characters
     * @type {string}
     * @memberof Order
     */
    invoiceAddress2?: string;
    /**
     * 
     * @type {string}
     * @memberof Order
     */
    invoiceCity: string;
    /**
     * Max length: 2 characters
     * @type {string}
     * @memberof Order
     */
    invoiceCountryCode: string;
    /**
     * Max length: 50 characters
     * @type {string}
     * @memberof Order
     */
    invoiceCustomerName: string;
    /**
     * Max length: 10 characters
     * @type {string}
     * @memberof Order
     */
    invoicePostalCode: string;
    /**
     * Max length: 50 characters
     * @type {string}
     * @memberof Order
     */
    deliveryMethodName?: string;
    /**
     * Max length: 50 characters
     * @type {string}
     * @memberof Order
     */
    deliveryMethodCode?: string;
    /**
     * Max length: 50 characters
     * @type {string}
     * @memberof Order
     */
    deliveryTermName?: string;
    /**
     * Max length: 50 characters
     * @type {string}
     * @memberof Order
     */
    deliveryTermCode?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Order
     */
    euThirdParty: boolean;
    /**
     * Purpose: The value relates to the property of the customer to whom it is assigned
     * @type {boolean}
     * @memberof Order
     */
    readonly customerIsPrivatePerson?: boolean;
    /**
     * Format: YYYY-MM-DD
     * @type {Date}
     * @memberof Order
     */
    orderDate: Date;
    /**
     * 
     * @type {number}
     * @memberof Order
     */
    status: OrderStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof Order
     */
    number?: number;
    /**
     * Format: YYYY-MM-DD. Default: null
     * @type {Date}
     * @memberof Order
     */
    deliveryDate?: Date;
    /**
     * 
     * @type {number}
     * @memberof Order
     */
    houseWorkAmount?: number;
    /**
     * 
     * @type {boolean}
     * @memberof Order
     */
    houseWorkAutomaticDistribution?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Order
     */
    houseWorkCorporateIdentityNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof Order
     */
    houseWorkPropertyName?: string;
    /**
     * 
     * @type {Array<OrderRow>}
     * @memberof Order
     */
    rows?: Array<OrderRow>;
    /**
     * Format: YYYY-MM-DD. Default: null
     * @type {Date}
     * @memberof Order
     */
    shippedDateTime?: Date;
    /**
     * 
     * @type {number}
     * @memberof Order
     */
    rotReducedInvoicingType: OrderRotReducedInvoicingTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof Order
     */
    rotPropertyType?: number;
    /**
     * 
     * @type {Array<SalesDocumentRotRutReductionPerson>}
     * @memberof Order
     */
    persons?: Array<SalesDocumentRotRutReductionPerson>;
    /**
     * 
     * @type {boolean}
     * @memberof Order
     */
    reverseChargeOnConstructionServices: boolean;
}

export function OrderFromJSON(json: any): Order {
    return OrderFromJSONTyped(json, false);
}

export function OrderFromJSONTyped(json: any, ignoreDiscriminator: boolean): Order {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'Id') ? undefined : json['Id'],
        'amount': json['Amount'],
        'customerId': json['CustomerId'],
        'currencyCode': json['CurrencyCode'],
        'vatAmount': json['VatAmount'],
        'roundingsAmount': json['RoundingsAmount'],
        'deliveredAmount': !exists(json, 'DeliveredAmount') ? undefined : json['DeliveredAmount'],
        'deliveredVatAmount': !exists(json, 'DeliveredVatAmount') ? undefined : json['DeliveredVatAmount'],
        'deliveredRoundingsAmount': !exists(json, 'DeliveredRoundingsAmount') ? undefined : json['DeliveredRoundingsAmount'],
        'deliveryCustomerName': !exists(json, 'DeliveryCustomerName') ? undefined : json['DeliveryCustomerName'],
        'deliveryAddress1': !exists(json, 'DeliveryAddress1') ? undefined : json['DeliveryAddress1'],
        'deliveryAddress2': !exists(json, 'DeliveryAddress2') ? undefined : json['DeliveryAddress2'],
        'deliveryPostalCode': !exists(json, 'DeliveryPostalCode') ? undefined : json['DeliveryPostalCode'],
        'deliveryCity': !exists(json, 'DeliveryCity') ? undefined : json['DeliveryCity'],
        'deliveryCountryCode': !exists(json, 'DeliveryCountryCode') ? undefined : json['DeliveryCountryCode'],
        'yourReference': !exists(json, 'YourReference') ? undefined : json['YourReference'],
        'ourReference': !exists(json, 'OurReference') ? undefined : json['OurReference'],
        'invoiceAddress1': !exists(json, 'InvoiceAddress1') ? undefined : json['InvoiceAddress1'],
        'invoiceAddress2': !exists(json, 'InvoiceAddress2') ? undefined : json['InvoiceAddress2'],
        'invoiceCity': json['InvoiceCity'],
        'invoiceCountryCode': json['InvoiceCountryCode'],
        'invoiceCustomerName': json['InvoiceCustomerName'],
        'invoicePostalCode': json['InvoicePostalCode'],
        'deliveryMethodName': !exists(json, 'DeliveryMethodName') ? undefined : json['DeliveryMethodName'],
        'deliveryMethodCode': !exists(json, 'DeliveryMethodCode') ? undefined : json['DeliveryMethodCode'],
        'deliveryTermName': !exists(json, 'DeliveryTermName') ? undefined : json['DeliveryTermName'],
        'deliveryTermCode': !exists(json, 'DeliveryTermCode') ? undefined : json['DeliveryTermCode'],
        'euThirdParty': json['EuThirdParty'],
        'customerIsPrivatePerson': !exists(json, 'CustomerIsPrivatePerson') ? undefined : json['CustomerIsPrivatePerson'],
        'orderDate': (new Date(json['OrderDate'])),
        'status': json['Status'],
        'number': !exists(json, 'Number') ? undefined : json['Number'],
        'deliveryDate': !exists(json, 'DeliveryDate') ? undefined : (new Date(json['DeliveryDate'])),
        'houseWorkAmount': !exists(json, 'HouseWorkAmount') ? undefined : json['HouseWorkAmount'],
        'houseWorkAutomaticDistribution': !exists(json, 'HouseWorkAutomaticDistribution') ? undefined : json['HouseWorkAutomaticDistribution'],
        'houseWorkCorporateIdentityNumber': !exists(json, 'HouseWorkCorporateIdentityNumber') ? undefined : json['HouseWorkCorporateIdentityNumber'],
        'houseWorkPropertyName': !exists(json, 'HouseWorkPropertyName') ? undefined : json['HouseWorkPropertyName'],
        'rows': !exists(json, 'Rows') ? undefined : ((json['Rows'] as Array<any>).map(OrderRowFromJSON)),
        'shippedDateTime': !exists(json, 'ShippedDateTime') ? undefined : (new Date(json['ShippedDateTime'])),
        'rotReducedInvoicingType': json['RotReducedInvoicingType'],
        'rotPropertyType': !exists(json, 'RotPropertyType') ? undefined : json['RotPropertyType'],
        'persons': !exists(json, 'Persons') ? undefined : ((json['Persons'] as Array<any>).map(SalesDocumentRotRutReductionPersonFromJSON)),
        'reverseChargeOnConstructionServices': json['ReverseChargeOnConstructionServices'],
    };
}

export function OrderToJSON(value?: Order | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Amount': value.amount,
        'CustomerId': value.customerId,
        'CurrencyCode': value.currencyCode,
        'VatAmount': value.vatAmount,
        'RoundingsAmount': value.roundingsAmount,
        'DeliveredAmount': value.deliveredAmount,
        'DeliveredVatAmount': value.deliveredVatAmount,
        'DeliveredRoundingsAmount': value.deliveredRoundingsAmount,
        'DeliveryCustomerName': value.deliveryCustomerName,
        'DeliveryAddress1': value.deliveryAddress1,
        'DeliveryAddress2': value.deliveryAddress2,
        'DeliveryPostalCode': value.deliveryPostalCode,
        'DeliveryCity': value.deliveryCity,
        'DeliveryCountryCode': value.deliveryCountryCode,
        'YourReference': value.yourReference,
        'OurReference': value.ourReference,
        'InvoiceAddress1': value.invoiceAddress1,
        'InvoiceAddress2': value.invoiceAddress2,
        'InvoiceCity': value.invoiceCity,
        'InvoiceCountryCode': value.invoiceCountryCode,
        'InvoiceCustomerName': value.invoiceCustomerName,
        'InvoicePostalCode': value.invoicePostalCode,
        'DeliveryMethodName': value.deliveryMethodName,
        'DeliveryMethodCode': value.deliveryMethodCode,
        'DeliveryTermName': value.deliveryTermName,
        'DeliveryTermCode': value.deliveryTermCode,
        'EuThirdParty': value.euThirdParty,
        'OrderDate': (value.orderDate.toISOString()),
        'Status': value.status,
        'Number': value.number,
        'DeliveryDate': value.deliveryDate === undefined ? undefined : (value.deliveryDate.toISOString()),
        'HouseWorkAmount': value.houseWorkAmount,
        'HouseWorkAutomaticDistribution': value.houseWorkAutomaticDistribution,
        'HouseWorkCorporateIdentityNumber': value.houseWorkCorporateIdentityNumber,
        'HouseWorkPropertyName': value.houseWorkPropertyName,
        'Rows': value.rows === undefined ? undefined : ((value.rows as Array<any>).map(OrderRowToJSON)),
        'ShippedDateTime': value.shippedDateTime === undefined ? undefined : (value.shippedDateTime.toISOString()),
        'RotReducedInvoicingType': value.rotReducedInvoicingType,
        'RotPropertyType': value.rotPropertyType,
        'Persons': value.persons === undefined ? undefined : ((value.persons as Array<any>).map(SalesDocumentRotRutReductionPersonToJSON)),
        'ReverseChargeOnConstructionServices': value.reverseChargeOnConstructionServices,
    };
}

/**
* @export
* @enum {string}
*/
export enum OrderStatusEnum {
    NUMBER_1 = 1,
    NUMBER_2 = 2,
    NUMBER_3 = 3
}
/**
* @export
* @enum {string}
*/
export enum OrderRotReducedInvoicingTypeEnum {
    NUMBER_0 = 0,
    NUMBER_1 = 1,
    NUMBER_2 = 2
}


