/* tslint:disable */
/* eslint-disable */
/**
 * Visma eAccounting API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RelatedAccounts
 */
export interface RelatedAccounts {
    /**
     * 
     * @type {number}
     * @memberof RelatedAccounts
     */
    accountNumber1?: number;
    /**
     * 
     * @type {number}
     * @memberof RelatedAccounts
     */
    accountNumber2?: number;
    /**
     * 
     * @type {number}
     * @memberof RelatedAccounts
     */
    accountNumber3?: number;
}

export function RelatedAccountsFromJSON(json: any): RelatedAccounts {
    return RelatedAccountsFromJSONTyped(json, false);
}

export function RelatedAccountsFromJSONTyped(json: any, ignoreDiscriminator: boolean): RelatedAccounts {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'accountNumber1': !exists(json, 'AccountNumber1') ? undefined : json['AccountNumber1'],
        'accountNumber2': !exists(json, 'AccountNumber2') ? undefined : json['AccountNumber2'],
        'accountNumber3': !exists(json, 'AccountNumber3') ? undefined : json['AccountNumber3'],
    };
}

export function RelatedAccountsToJSON(value?: RelatedAccounts | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'AccountNumber1': value.accountNumber1,
        'AccountNumber2': value.accountNumber2,
        'AccountNumber3': value.accountNumber3,
    };
}


