/* tslint:disable */
/* eslint-disable */
/**
 * Visma eAccounting API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SalesDocumentRotRutReductionPerson
 */
export interface SalesDocumentRotRutReductionPerson {
    /**
     * Purpose: Social security number
     * @type {string}
     * @memberof SalesDocumentRotRutReductionPerson
     */
    ssn: string;
    /**
     * 
     * @type {number}
     * @memberof SalesDocumentRotRutReductionPerson
     */
    amount: number;
}

export function SalesDocumentRotRutReductionPersonFromJSON(json: any): SalesDocumentRotRutReductionPerson {
    return SalesDocumentRotRutReductionPersonFromJSONTyped(json, false);
}

export function SalesDocumentRotRutReductionPersonFromJSONTyped(json: any, ignoreDiscriminator: boolean): SalesDocumentRotRutReductionPerson {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ssn': json['Ssn'],
        'amount': json['Amount'],
    };
}

export function SalesDocumentRotRutReductionPersonToJSON(value?: SalesDocumentRotRutReductionPerson | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Ssn': value.ssn,
        'Amount': value.amount,
    };
}


