/* tslint:disable */
/* eslint-disable */
/**
 * Visma eAccounting API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SupplierInvoiceRow
 */
export interface SupplierInvoiceRow {
    /**
     * 
     * @type {string}
     * @memberof SupplierInvoiceRow
     */
    id?: string;
    /**
     * 
     * @type {number}
     * @memberof SupplierInvoiceRow
     */
    accountNumber?: number;
    /**
     * 
     * @type {string}
     * @memberof SupplierInvoiceRow
     */
    vadCodeId?: string;
    /**
     * 
     * @type {string}
     * @memberof SupplierInvoiceRow
     */
    costCenterItemId1?: string;
    /**
     * 
     * @type {string}
     * @memberof SupplierInvoiceRow
     */
    costCenterItemId2?: string;
    /**
     * 
     * @type {string}
     * @memberof SupplierInvoiceRow
     */
    costCenterItemId3?: string;
    /**
     * 
     * @type {number}
     * @memberof SupplierInvoiceRow
     */
    quantity?: number;
    /**
     * 
     * @type {number}
     * @memberof SupplierInvoiceRow
     */
    weight?: number;
    /**
     * 
     * @type {Date}
     * @memberof SupplierInvoiceRow
     */
    deliveryDate?: Date;
    /**
     * 
     * @type {number}
     * @memberof SupplierInvoiceRow
     */
    harvestYear?: number;
    /**
     * 
     * @type {number}
     * @memberof SupplierInvoiceRow
     */
    debetAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof SupplierInvoiceRow
     */
    creditAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof SupplierInvoiceRow
     */
    lineNumber?: number;
    /**
     * 
     * @type {string}
     * @memberof SupplierInvoiceRow
     */
    projectId?: string;
    /**
     * 
     * @type {string}
     * @memberof SupplierInvoiceRow
     */
    transactionText?: string;
}

export function SupplierInvoiceRowFromJSON(json: any): SupplierInvoiceRow {
    return SupplierInvoiceRowFromJSONTyped(json, false);
}

export function SupplierInvoiceRowFromJSONTyped(json: any, ignoreDiscriminator: boolean): SupplierInvoiceRow {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'Id') ? undefined : json['Id'],
        'accountNumber': !exists(json, 'AccountNumber') ? undefined : json['AccountNumber'],
        'vadCodeId': !exists(json, 'VadCodeId') ? undefined : json['VadCodeId'],
        'costCenterItemId1': !exists(json, 'CostCenterItemId1') ? undefined : json['CostCenterItemId1'],
        'costCenterItemId2': !exists(json, 'CostCenterItemId2') ? undefined : json['CostCenterItemId2'],
        'costCenterItemId3': !exists(json, 'CostCenterItemId3') ? undefined : json['CostCenterItemId3'],
        'quantity': !exists(json, 'Quantity') ? undefined : json['Quantity'],
        'weight': !exists(json, 'Weight') ? undefined : json['Weight'],
        'deliveryDate': !exists(json, 'DeliveryDate') ? undefined : (new Date(json['DeliveryDate'])),
        'harvestYear': !exists(json, 'HarvestYear') ? undefined : json['HarvestYear'],
        'debetAmount': !exists(json, 'DebetAmount') ? undefined : json['DebetAmount'],
        'creditAmount': !exists(json, 'CreditAmount') ? undefined : json['CreditAmount'],
        'lineNumber': !exists(json, 'LineNumber') ? undefined : json['LineNumber'],
        'projectId': !exists(json, 'ProjectId') ? undefined : json['ProjectId'],
        'transactionText': !exists(json, 'TransactionText') ? undefined : json['TransactionText'],
    };
}

export function SupplierInvoiceRowToJSON(value?: SupplierInvoiceRow | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Id': value.id,
        'AccountNumber': value.accountNumber,
        'VadCodeId': value.vadCodeId,
        'CostCenterItemId1': value.costCenterItemId1,
        'CostCenterItemId2': value.costCenterItemId2,
        'CostCenterItemId3': value.costCenterItemId3,
        'Quantity': value.quantity,
        'Weight': value.weight,
        'DeliveryDate': value.deliveryDate === undefined ? undefined : (value.deliveryDate.toISOString()),
        'HarvestYear': value.harvestYear,
        'DebetAmount': value.debetAmount,
        'CreditAmount': value.creditAmount,
        'LineNumber': value.lineNumber,
        'ProjectId': value.projectId,
        'TransactionText': value.transactionText,
    };
}


