/* tslint:disable */
/* eslint-disable */
/**
 * Visma eAccounting API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SupplierInvoiceDraftAllocationPlan
 */
export interface SupplierInvoiceDraftAllocationPlan {
    /**
     * 
     * @type {string}
     * @memberof SupplierInvoiceDraftAllocationPlan
     */
    supplierInvoiceDraftRowId: string;
    /**
     * 
     * @type {Date}
     * @memberof SupplierInvoiceDraftAllocationPlan
     */
    bookkeepingStartDate?: Date;
    /**
     * 
     * @type {number}
     * @memberof SupplierInvoiceDraftAllocationPlan
     */
    amountToAllocate?: number;
    /**
     * 
     * @type {number}
     * @memberof SupplierInvoiceDraftAllocationPlan
     */
    quantityToAllocate?: number;
    /**
     * 
     * @type {number}
     * @memberof SupplierInvoiceDraftAllocationPlan
     */
    weightToAllocate?: number;
    /**
     * 
     * @type {number}
     * @memberof SupplierInvoiceDraftAllocationPlan
     */
    allocationAccountNumber?: number;
    /**
     * 
     * @type {number}
     * @memberof SupplierInvoiceDraftAllocationPlan
     */
    numberOfAllocationPeriods?: number;
}

export function SupplierInvoiceDraftAllocationPlanFromJSON(json: any): SupplierInvoiceDraftAllocationPlan {
    return SupplierInvoiceDraftAllocationPlanFromJSONTyped(json, false);
}

export function SupplierInvoiceDraftAllocationPlanFromJSONTyped(json: any, ignoreDiscriminator: boolean): SupplierInvoiceDraftAllocationPlan {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'supplierInvoiceDraftRowId': json['SupplierInvoiceDraftRowId'],
        'bookkeepingStartDate': !exists(json, 'BookkeepingStartDate') ? undefined : (new Date(json['BookkeepingStartDate'])),
        'amountToAllocate': !exists(json, 'AmountToAllocate') ? undefined : json['AmountToAllocate'],
        'quantityToAllocate': !exists(json, 'QuantityToAllocate') ? undefined : json['QuantityToAllocate'],
        'weightToAllocate': !exists(json, 'WeightToAllocate') ? undefined : json['WeightToAllocate'],
        'allocationAccountNumber': !exists(json, 'AllocationAccountNumber') ? undefined : json['AllocationAccountNumber'],
        'numberOfAllocationPeriods': !exists(json, 'NumberOfAllocationPeriods') ? undefined : json['NumberOfAllocationPeriods'],
    };
}

export function SupplierInvoiceDraftAllocationPlanToJSON(value?: SupplierInvoiceDraftAllocationPlan | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'SupplierInvoiceDraftRowId': value.supplierInvoiceDraftRowId,
        'BookkeepingStartDate': value.bookkeepingStartDate === undefined ? undefined : (value.bookkeepingStartDate.toISOString()),
        'AmountToAllocate': value.amountToAllocate,
        'QuantityToAllocate': value.quantityToAllocate,
        'WeightToAllocate': value.weightToAllocate,
        'AllocationAccountNumber': value.allocationAccountNumber,
        'NumberOfAllocationPeriods': value.numberOfAllocationPeriods,
    };
}


