/* tslint:disable */
/* eslint-disable */
/**
 * Visma eAccounting API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TermsOfPayment
 */
export interface TermsOfPayment {
    /**
     * Purpose: Unique Id provided by eAccounting
     * @type {string}
     * @memberof TermsOfPayment
     */
    readonly id?: string;
    /**
     * 
     * @type {string}
     * @memberof TermsOfPayment
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof TermsOfPayment
     */
    nameEnglish?: string;
    /**
     * 
     * @type {number}
     * @memberof TermsOfPayment
     */
    numberOfDays?: number;
    /**
     * 
     * @type {number}
     * @memberof TermsOfPayment
     */
    termsOfPaymentTypeId?: number;
    /**
     * 
     * @type {string}
     * @memberof TermsOfPayment
     */
    termsOfPaymentTypeText?: string;
}

export function TermsOfPaymentFromJSON(json: any): TermsOfPayment {
    return TermsOfPaymentFromJSONTyped(json, false);
}

export function TermsOfPaymentFromJSONTyped(json: any, ignoreDiscriminator: boolean): TermsOfPayment {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'Id') ? undefined : json['Id'],
        'name': !exists(json, 'Name') ? undefined : json['Name'],
        'nameEnglish': !exists(json, 'NameEnglish') ? undefined : json['NameEnglish'],
        'numberOfDays': !exists(json, 'NumberOfDays') ? undefined : json['NumberOfDays'],
        'termsOfPaymentTypeId': !exists(json, 'TermsOfPaymentTypeId') ? undefined : json['TermsOfPaymentTypeId'],
        'termsOfPaymentTypeText': !exists(json, 'TermsOfPaymentTypeText') ? undefined : json['TermsOfPaymentTypeText'],
    };
}

export function TermsOfPaymentToJSON(value?: TermsOfPayment | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Name': value.name,
        'NameEnglish': value.nameEnglish,
        'NumberOfDays': value.numberOfDays,
        'TermsOfPaymentTypeId': value.termsOfPaymentTypeId,
        'TermsOfPaymentTypeText': value.termsOfPaymentTypeText,
    };
}


