/* tslint:disable */
/* eslint-disable */
/**
 * Visma eAccounting API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VoucherRow
 */
export interface VoucherRow {
    /**
     * 
     * @type {number}
     * @memberof VoucherRow
     */
    accountNumber: number;
    /**
     * Format: Max 2 decimals
     * @type {number}
     * @memberof VoucherRow
     */
    debetAmount?: number;
    /**
     * Format: Max 2 decimals
     * @type {number}
     * @memberof VoucherRow
     */
    creditAmount?: number;
    /**
     * Max length: 50 characters
     * @type {string}
     * @memberof VoucherRow
     */
    transactionText?: string;
    /**
     * Source: Get from /v1/costcenters
     * @type {string}
     * @memberof VoucherRow
     */
    costCenterItemId1?: string;
    /**
     * Source: Get from /v1/costcenters
     * @type {string}
     * @memberof VoucherRow
     */
    costCenterItemId2?: string;
    /**
     * Source: Get from /v1/costcenters
     * @type {string}
     * @memberof VoucherRow
     */
    costCenterItemId3?: string;
    /**
     * Format: Max 2 decimals
     * Purpose: This feature is for dutch companies only which enabled agriculture support
     * @type {number}
     * @memberof VoucherRow
     */
    quantity?: number;
    /**
     * Format: Max 2 decimals
     * Purpose: This feature is for dutch companies only which enabled agriculture support
     * @type {number}
     * @memberof VoucherRow
     */
    weight?: number;
    /**
     * Format: YYYY-MM-DD
     * Purpose: This feature is for dutch companies only which enabled agriculture support
     * @type {Date}
     * @memberof VoucherRow
     */
    deliveryDate?: Date;
    /**
     * Purpose: This feature is for dutch companies only which enabled agriculture support
     * @type {number}
     * @memberof VoucherRow
     */
    harvestYear?: number;
    /**
     * 
     * @type {string}
     * @memberof VoucherRow
     */
    vatCodeId?: string;
    /**
     * 
     * @type {string}
     * @memberof VoucherRow
     */
    vatCode?: string;
    /**
     * Source: Get from /v1/projects
     * @type {string}
     * @memberof VoucherRow
     */
    projectId?: string;
}

export function VoucherRowFromJSON(json: any): VoucherRow {
    return VoucherRowFromJSONTyped(json, false);
}

export function VoucherRowFromJSONTyped(json: any, ignoreDiscriminator: boolean): VoucherRow {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'accountNumber': json['AccountNumber'],
        'debetAmount': !exists(json, 'DebetAmount') ? undefined : json['DebetAmount'],
        'creditAmount': !exists(json, 'CreditAmount') ? undefined : json['CreditAmount'],
        'transactionText': !exists(json, 'TransactionText') ? undefined : json['TransactionText'],
        'costCenterItemId1': !exists(json, 'CostCenterItemId1') ? undefined : json['CostCenterItemId1'],
        'costCenterItemId2': !exists(json, 'CostCenterItemId2') ? undefined : json['CostCenterItemId2'],
        'costCenterItemId3': !exists(json, 'CostCenterItemId3') ? undefined : json['CostCenterItemId3'],
        'quantity': !exists(json, 'Quantity') ? undefined : json['Quantity'],
        'weight': !exists(json, 'Weight') ? undefined : json['Weight'],
        'deliveryDate': !exists(json, 'DeliveryDate') ? undefined : (new Date(json['DeliveryDate'])),
        'harvestYear': !exists(json, 'HarvestYear') ? undefined : json['HarvestYear'],
        'vatCodeId': !exists(json, 'VatCodeId') ? undefined : json['VatCodeId'],
        'vatCode': !exists(json, 'VatCode') ? undefined : json['VatCode'],
        'projectId': !exists(json, 'ProjectId') ? undefined : json['ProjectId'],
    };
}

export function VoucherRowToJSON(value?: VoucherRow | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'AccountNumber': value.accountNumber,
        'DebetAmount': value.debetAmount,
        'CreditAmount': value.creditAmount,
        'TransactionText': value.transactionText,
        'CostCenterItemId1': value.costCenterItemId1,
        'CostCenterItemId2': value.costCenterItemId2,
        'CostCenterItemId3': value.costCenterItemId3,
        'Quantity': value.quantity,
        'Weight': value.weight,
        'DeliveryDate': value.deliveryDate === undefined ? undefined : (value.deliveryDate.toISOString()),
        'HarvestYear': value.harvestYear,
        'VatCodeId': value.vatCodeId,
        'VatCode': value.vatCode,
        'ProjectId': value.projectId,
    };
}


