/* tslint:disable */
/* eslint-disable */
/**
 * Visma eAccounting API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    AttachmentLink,
    AttachmentLinkFromJSON,
    AttachmentLinkToJSON,
} from '../models';

export interface AttachmentLinksPostRequest {
    attachmentLinks: AttachmentLink;
}

/**
 * 
 */
export class AttachmentLinksApi extends runtime.BaseAPI {

    /**
     * <p>Requires any of the following scopes: <br><b>ea:accounting, ea:purchase</b></p><p>Available in any of the following variants: <br><b>Pro, Standard, Invoicing, Bookkeeping, Solo</b></p>
     * Create a new attachmentlink.
     */
    async attachmentLinksPostRaw(requestParameters: AttachmentLinksPostRequest): Promise<runtime.ApiResponse<AttachmentLink>> {
        if (requestParameters.attachmentLinks === null || requestParameters.attachmentLinks === undefined) {
            throw new runtime.RequiredError('attachmentLinks','Required parameter requestParameters.attachmentLinks was null or undefined when calling attachmentLinksPost.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/attachmentlinks`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AttachmentLinkToJSON(requestParameters.attachmentLinks),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => AttachmentLinkFromJSON(jsonValue));
    }

    /**
     * <p>Requires any of the following scopes: <br><b>ea:accounting, ea:purchase</b></p><p>Available in any of the following variants: <br><b>Pro, Standard, Invoicing, Bookkeeping, Solo</b></p>
     * Create a new attachmentlink.
     */
    async attachmentLinksPost(requestParameters: AttachmentLinksPostRequest): Promise<AttachmentLink> {
        const response = await this.attachmentLinksPostRaw(requestParameters);
        return await response.value();
    }

}
