/* tslint:disable */
/* eslint-disable */
/**
 * Visma eAccounting API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    CustomerInvoice,
    CustomerInvoiceFromJSON,
    CustomerInvoiceToJSON,
} from '../models';

export interface CustomerInvoicesGetRequest {
    invoiceId: string;
}

/**
 * 
 */
export class CustomerInvoicesApi extends runtime.BaseAPI {

    /**
     * <p>Requires any of the following scopes: <br><b>ea:sales, ea:sales_readonly</b></p><p>Available in any of the following variants: <br><b>Pro, Standard, Invoicing, Solo</b></p>
     * Gets a customer invoice with a specific id.
     */
    async customerInvoicesGetRaw(requestParameters: CustomerInvoicesGetRequest): Promise<runtime.ApiResponse<CustomerInvoice>> {
        if (requestParameters.invoiceId === null || requestParameters.invoiceId === undefined) {
            throw new runtime.RequiredError('invoiceId','Required parameter requestParameters.invoiceId was null or undefined when calling customerInvoicesGet.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/customerinvoices/{invoiceId}`.replace(`{${"invoiceId"}}`, encodeURIComponent(String(requestParameters.invoiceId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomerInvoiceFromJSON(jsonValue));
    }

    /**
     * <p>Requires any of the following scopes: <br><b>ea:sales, ea:sales_readonly</b></p><p>Available in any of the following variants: <br><b>Pro, Standard, Invoicing, Solo</b></p>
     * Gets a customer invoice with a specific id.
     */
    async customerInvoicesGet(requestParameters: CustomerInvoicesGetRequest): Promise<CustomerInvoice> {
        const response = await this.customerInvoicesGetRaw(requestParameters);
        return await response.value();
    }

}
