/* tslint:disable */
/* eslint-disable */
/**
 * Visma eAccounting API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    CustomerInvoice,
    CustomerInvoiceFromJSON,
    CustomerInvoiceToJSON,
    CustomerInvoicePaidByCreditCard,
    CustomerInvoicePaidByCreditCardFromJSON,
    CustomerInvoicePaidByCreditCardToJSON,
} from '../models';

export interface CustomerInvoicesPaidByCreditCardPostRequest {
    paidCustomerInvoiceDraft: CustomerInvoicePaidByCreditCard;
}

/**
 * 
 */
export class CustomerInvoicesPaidByCreditCardApi extends runtime.BaseAPI {

    /**
     * <p>Requires any of the following scopes: <br><b>ea:sales</b></p><p>Available in any of the following variants: <br><b>Pro, Standard, Invoicing, Solo</b></p>
     */
    async customerInvoicesPaidByCreditCardPostRaw(requestParameters: CustomerInvoicesPaidByCreditCardPostRequest): Promise<runtime.ApiResponse<CustomerInvoice>> {
        if (requestParameters.paidCustomerInvoiceDraft === null || requestParameters.paidCustomerInvoiceDraft === undefined) {
            throw new runtime.RequiredError('paidCustomerInvoiceDraft','Required parameter requestParameters.paidCustomerInvoiceDraft was null or undefined when calling customerInvoicesPaidByCreditCardPost.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/customerinvoicespaidbycreditcard`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CustomerInvoicePaidByCreditCardToJSON(requestParameters.paidCustomerInvoiceDraft),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomerInvoiceFromJSON(jsonValue));
    }

    /**
     * <p>Requires any of the following scopes: <br><b>ea:sales</b></p><p>Available in any of the following variants: <br><b>Pro, Standard, Invoicing, Solo</b></p>
     */
    async customerInvoicesPaidByCreditCardPost(requestParameters: CustomerInvoicesPaidByCreditCardPostRequest): Promise<CustomerInvoice> {
        const response = await this.customerInvoicesPaidByCreditCardPostRaw(requestParameters);
        return await response.value();
    }

}
