/* tslint:disable */
/* eslint-disable */
/**
 * Visma eAccounting API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    SupplierListItem,
    SupplierListItemFromJSON,
    SupplierListItemToJSON,
} from '../models';

export interface SupplierListItemsGetRequest {
    changedFromDate?: string;
    includeInactive?: boolean;
}

/**
 * 
 */
export class SupplierListItemsApi extends runtime.BaseAPI {

    /**
     * <p>Requires any of the following scopes: <br><b>ea:purchase, ea:purchase_readonly</b></p><p>Available in any of the following variants: <br><b>Pro, Standard, Solo</b></p>
     * Get a list of all suppliers. Filter by excluding inactive or changed from date (yyyy-MM-dd) or date(yyyy-MM-dd hh:mm:ss).
     */
    async supplierListItemsGetRaw(requestParameters: SupplierListItemsGetRequest): Promise<runtime.ApiResponse<Array<SupplierListItem>>> {
        const queryParameters: runtime.HTTPQuery = {};

        if (requestParameters.changedFromDate !== undefined) {
            queryParameters['changedFromDate'] = requestParameters.changedFromDate;
        }

        if (requestParameters.includeInactive !== undefined) {
            queryParameters['includeInactive'] = requestParameters.includeInactive;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/supplierlistitems`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SupplierListItemFromJSON));
    }

    /**
     * <p>Requires any of the following scopes: <br><b>ea:purchase, ea:purchase_readonly</b></p><p>Available in any of the following variants: <br><b>Pro, Standard, Solo</b></p>
     * Get a list of all suppliers. Filter by excluding inactive or changed from date (yyyy-MM-dd) or date(yyyy-MM-dd hh:mm:ss).
     */
    async supplierListItemsGet(requestParameters: SupplierListItemsGetRequest): Promise<Array<SupplierListItem>> {
        const response = await this.supplierListItemsGetRaw(requestParameters);
        return await response.value();
    }

}
